### ISSUE TITLE
Hardsuit bugs.

### ISSUE THREAD

**Issue by Jakksergal** [NEV-Unity/NEV-Unity#5]
You are unable to remove any attachment you place on a hardsuit. I've tried every tool but there's no effect.
- Probably has a patch on Aurora

Suit cyclers are unable to cycle a hardsuit with any attachments on it.
- Probably has a patch on Aurora.

This makes for an amazingly infuriating bug combo.

**Comment by Jamini** [comment]
You need to target the correct zone to remove attachments and use a screwdriver.

Head for helmets
A foot for magboos
Mouth for breath masks

Cyclers not functioning with hardsuits that have attachments is intended behavior. To prevent accidental deletion of magboots and breathmasks.

Closing this.

**Comment by Jakksergal** [comment]
.. Right.. YE OLDE' baycode, I forgot.
