### ISSUE TITLE
Mapping Mega Issue Report

### ISSUE THREAD

**Issue by Jakksergal** [NEV-Unity/NEV-Unity#6]
This will be my personal report on things wrong with the map. Don't mark this as solved until we're in v1.0 of the map. I'll try to check off complete items as they're solved.
### Access
- [ ] !! Hydroponics maintenance has no hydroponics access to it, it is just plain maintenance.
- [ ] !! Escape pod exterior doors have access on them. This would be fine if they were instructed to open when an emergency shuttle was called, but I don't know if that's programmed to happen or not.
- [ ] !! Atmos tech's have fuck all access. 
  -   Does not have access to engineering storage.
  -   Does not have access to engineering EVA/suit cycler.
- [ ] !! The maintenance door to the end-line disposal area (Cargo side) is pure maintenance access. Meaning engineers can access cargo.
### Structure
- [ ] !! South of the security shrotpod there's an opening to space, I have no idea why it's there.
- [ ] !! The yellow pipes traveling from atmos to the engineering control room are not hidden.
- [ ] !! There's a random SMES in maintenance by the janitor's closet. IT does not charge, it only outputs and starts off by default.
- [ ] !! There's a massive chunk of walling north of atmos where two fire fighting closets reside. It's just a waste of space.
- [ ] !! There is hardly any room in atmos for existing-system modification, which is the only thing Atmos tech's have to do on extended. (Pet Peeve)
- [ ] !! Escape pod by Security is just.. Stupid. I'm calling it the shortbus or shortpod until it's fixed.
- [ ] !! End-line disposal conveyors are configured incorrectly. 
  ### Items
- [ ] !! There is a bananium coin in the QM's office, what the fuck were you thinking?
- [ ] !! It is extremely difficult to put back the atoms pipe dispenser if it is removed from its starting location. (Especially for new players)
- [ ] !! The hidden items by the HoP's office don't spawn a lot of the time.
###### Dating

!! = Week of 7/12-18/2015

**Comment by Jamini** [comment]
This is not the place for this
